services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  gameserver:
    build:
      context: .
      dockerfile: GameServer/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
      - sqlserver

  frontend:
    build:
      context: ./multiplayer-game-ui
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - gameserver